"""Add study_year_id to users

Revision ID: 3c98adf30d28
Revises: fbda79a5ccf5
Create Date: 2026-07-04 21:21:34.571817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c98adf30d28'
down_revision: Union[str, Sequence[str], None] = 'fbda79a5ccf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('study_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'study_years', ['study_year_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'study_year_id')
    # ### end Alembic commands ###
