"""add head_id to faculty and dept

Revision ID: f77893ec846a
Revises: 5b3a83c7ef88
Create Date: 2026-07-07 20:14:03.853549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77893ec846a'
down_revision: Union[str, Sequence[str], None] = '5b3a83c7ef88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'], ondelete='SET NULL')
    op.add_column('faculties', sa.Column('head_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'faculties', 'users', ['head_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculties', type_='foreignkey')
    op.drop_column('faculties', 'head_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_id')
    # ### end Alembic commands ###
